# Generated by Django 4.2 on 2023-10-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshorter', '0003_alter_urlshortener_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlshortener',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='long_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='urlshortener',
            name='short_url',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
