# Generated by Django 4.2 on 2023-10-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshorter', '0004_alter_urlshortener_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='no_of_count',
            field=models.IntegerField(default=0),
        ),
    ]
