# Generated by Django 4.2 on 2023-10-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshorter', '0005_urlshortener_no_of_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlshortener',
            options={},
        ),
    ]
